# Generated by Django 4.1.4 on 2022-12-26 11:31

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=80, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=60)),
                ('nivel', models.IntegerField(null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombrecatg', models.CharField(max_length=20, unique=True, verbose_name='Nombre')),
                ('reference', models.CharField(max_length=40, null=True, unique=True, verbose_name='Referencia')),
                ('disponible', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=200)),
                ('nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=20)),
                ('telefono2', models.CharField(max_length=20, null=True)),
                ('correo', models.CharField(max_length=100)),
                ('correo2', models.CharField(max_length=100, null=True)),
                ('activo', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('NombreMarca', models.CharField(max_length=20, unique=True, verbose_name='Nombre Marca')),
                ('disponible', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Opciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda', models.CharField(max_length=20, null=True)),
                ('valor_iva', models.IntegerField(unique=True)),
                ('nombre_negocio', models.CharField(max_length=25, null=True)),
                ('mensaje_factura', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=200)),
                ('nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=20)),
                ('telefono2', models.CharField(max_length=20, null=True)),
                ('correo', models.CharField(max_length=100)),
                ('correo2', models.CharField(max_length=100, null=True)),
                ('activo', models.BooleanField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReporteProdPdf',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoriarid', models.IntegerField()),
                ('Activoid', models.BooleanField(null=True)),
                ('Tieneiva', models.BooleanField(null=True)),
                ('deposito', models.CharField(max_length=20)),
                ('nivel', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codbar', models.CharField(max_length=44, null=True, unique=True, verbose_name='CodBarra')),
                ('descripcionAmp', models.TextField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('descripcion', models.CharField(max_length=40, verbose_name='Nombre del Producto')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=9)),
                ('disponible', models.IntegerField(default=0, verbose_name='Unidades Disponibles')),
                ('categoria', models.CharField(choices=[('1', 'Unidad'), ('2', 'Kilo'), ('3', 'Litro'), ('4', 'Otros')], max_length=20, verbose_name='Tipo de Medida')),
                ('tiene_iva', models.BooleanField(default=True, null=True)),
                ('Activo', models.BooleanField(default=True, null=True)),
                ('Deposito', models.CharField(blank=True, max_length=44, verbose_name='Ubicación Unidades')),
                ('MinUnidades', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Exist. Unidades Mininas')),
                ('MaxUnidades', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Exist. Unidades Maximas')),
                ('Nivel', models.CharField(choices=[('1', 'Existencia en cero'), ('2', 'Existencia Disponible'), ('3', 'Por debajo del Minino'), ('4', 'Por Encima del Nivel')], default='2', max_length=1, verbose_name='Nivel')),
                ('category', models.ForeignKey(db_column='category_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.categoria', verbose_name='Categoria')),
                ('marca', models.ForeignKey(db_column='marca_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.marca', verbose_name='Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('sub_monto', models.DecimalField(decimal_places=2, max_digits=20)),
                ('monto_general', models.DecimalField(decimal_places=2, max_digits=20)),
                ('presente', models.BooleanField(null=True)),
                ('iva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.opciones', to_field='valor_iva')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.proveedor', to_field='cedula')),
            ],
        ),
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('sub_monto', models.DecimalField(decimal_places=2, max_digits=20)),
                ('monto_general', models.DecimalField(decimal_places=2, max_digits=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.cliente', to_field='cedula')),
                ('iva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.opciones', to_field='valor_iva')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.pedido')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('id_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.factura')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
        ),
    ]
